"""Add privilege

Revision ID: b6b791d6d837
Revises: 71ebbfd6b7ba
Create Date: 2023-01-02 22:01:20.646648

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6b791d6d837"
down_revision = "71ebbfd6b7ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "privileges",
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("can_manage_chat", sa.Boolean(), nullable=True),
        sa.Column("can_delete_messages", sa.Boolean(), nullable=True),
        sa.Column("can_manage_video_chats", sa.Boolean(), nullable=True),
        sa.Column("can_restrict_members", sa.Boolean(), nullable=True),
        sa.Column("can_promote_members", sa.Boolean(), nullable=True),
        sa.Column("can_change_info", sa.Boolean(), nullable=True),
        sa.Column("can_invite_users", sa.Boolean(), nullable=True),
        sa.Column("can_pin_messages", sa.Boolean(), nullable=True),
        sa.Column("is_anonymous", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("group_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("privileges")
    # ### end Alembic commands ###
