"""Add user and logs

Revision ID: c35df588b898
Revises: 
Create Date: 2022-10-09 01:19:12.635613

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c35df588b898"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("triggered_by", sa.BigInteger(), nullable=False),
        sa.Column("triggered_at", sa.BigInteger(), nullable=False),
        sa.Column("triggered_function", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "OWNER",
                "EXECUTOR",
                "WHITE",
                "BLACK",
                "OTHER",
                name="permissionlevel",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("records")
    # ### end Alembic commands ###
    op.execute("""DROP TYPE permissionlevel""")
